### ISSUE TITLE
how to set shpfile  Dimension type

### ISSUE THREAD

**Issue by bouyeijiang** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#16]
var writer =new ShapefileDataWriter(fullpath, factory,writeEncoding);
                writer.Header = ShapefileDataWriter.GetHeader(lines[0], lines.Count);

default is 3D coordinates? i need to 2d

**Comment by KubaSzostak** [comment]
Support for a custom-managed stream, which allows shapes to be written to it, has been added in the [successor](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri) library. There is also a [sample code](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/blob/develop/test/NetTopologySuite.IO.Esri.Test/Deprecated/Writers/ShapeFileDataWriterTest.cs)  demonstrating how to use different dimensions.
