### ISSUE TITLE
set encoding bug

### ISSUE THREAD

**Issue by bouyeijiang** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#19]
set encoding error:
this my code sample:
 ShapefileDataWriter.GetHeader(features[0], features.Count,Encoding.UTF8); 
error msg:
Setting the encoding is only allowed once, either by means of the constructor or this property setter

and  chinese random code error

**Comment by vuggg** [comment]
I just have tried the file you upload above:

Before convert: stösst auf den rendeler pfad
After convert: stÃ¶sst auf den rendeler pfad

Is that work correctly?

**Comment by akamsteeg** [comment]
I worked around this issue by setting an encoding in the constructor too:

```csharp
this._shapeFileWriter = new ShapefileDataWriter(streamRegistry, geometryFactory, Encoding.Default);
```

And I'm using the same encoding when writing the header:
```csharp
this._shapeFileWriter.Header = ShapefileDataWriter.GetHeader(this._features[0], this._features.Count, Encoding.Default);
```

**Comment by KubaSzostak** [comment]
Support for a different encodings has been added in the [successor](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri) library. There is also a [sample code](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/blob/develop/test/NetTopologySuite.IO.Esri.Test/Deprecated/Headers/ShapeFileEncodingTest.cs) demonstrating how to custom encoding.
