### ISSUE TITLE
DbaseFileReader default encoding error and so on...

### ISSUE THREAD

**Issue by bouyeijiang** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#21]
question 1:
var reader= new DbaseFileReader(file,encoding);
throw an error and that the object  not instance ;
question 2:
for example code;
 while (reader.Read())
                {
                    var f = new Feature() { Geometry = reader.Geometry };
                    f.Attributes = new AttributesTable();
                    int num = reader.DbaseHeader.NumFields;

                    for (int i = 0; i < num; ++i)
                    {
                        _name = reader.DbaseHeader.Fields[i].Name;
                        object val = reader.GetValue(i+1);//here is bug,attrbiute table not match column name index
                    }
};
question 3:
ShapefileDataWriter can't setting default encoding

**Comment by Conscientious** [comment]
May I ask how the solution was finally solved? Could you share the method?

**Comment by bouyeijiang** [comment]
谢谢您的来信！我会及时查阅的

**Comment by Conscientious** [comment]
朋友，请问你编码的问题最后是如何解决的？

**Comment by KubaSzostak** [comment]
I would like to remind you that the development of this project has been [discontinued](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/issues/82) and will be no longer maintained. Please consider [NetTopologySuite.IO.Esri](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri) as a replacement. It contains rewritten logic for dBase reader. If the problem still exist, [submit an issue](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/issues) directly in the new project, please.
