### ISSUE TITLE
dbf error

### ISSUE THREAD

**Issue by bouyeijiang** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#22]
when i write attribute column length more than 254   that string intercepted,can't write over length 254

on the other hand.ShapefileDataWriter About Chinese random encoding error

**Comment by KubaSzostak** [comment]
According to the [dBASE specification](https://www.dbase.com/help/11_2/Design_Tables/IDH_TABLEDES_FIELD_TYPES.htm) the Character field has maximum size of 254. Therefore writing over length 254 is not supported.
