### ISSUE TITLE
[BUG] UTF-8 read encoding error

### ISSUE THREAD

**Issue by sabvente** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#25]
**Describe**
UTF-8 shapefile loaded with wrong encoding.

**Code Snippet**
```csharp
using (var reader = new ShapefileDataReader("shape.shp", new GeometryFactory(),
    Encoding.UTF8))
{
    reader.Read();
}
```

**Investigation**
`NetTopologySuite.IO.DbaseFileReader.CreateStreamProviderRegistry` method gets called at`ShapefileDataReader` constructor.
It passes `encoding.EncodingName` to `ByteStreamProvider` argument with `"Unicode (UTF-8)"` value.

Later, when parsing the header in `NetTopologySuite.IO.DbaseFileHeader.GetEncoding()`
```csharp
try
{
    // The following line throws exception
    // 'Unicode (UTF-8)' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
    return DbaseEncodingUtility.GetEncodingForCodePageName(cpgText);
}
catch
{
    return DefaultEncoding;
}
```
I think `DbaseEncodingUtility.GetEncodingForCodePageName` should be called with "UTF-8" argument.

**Registering encoding provider**
Calling `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);` does not fixes my issue.

**Quick fix**
Setting the default header encoding.
```csharp
DbaseFileHeader.DefaultEncoding = Encoding.UTF8;
```

**Comment by Conscientious** [comment]
> **Describe** UTF-8 shapefile loaded with wrong encoding.
> 
> **Code Snippet**
> 
> ```cs
> using (var reader = new ShapefileDataReader("shape.shp", new GeometryFactory(),
>     Encoding.UTF8))
> {
>     reader.Read();
> }
> ```
> 
> **Investigation** `NetTopologySuite.IO.DbaseFileReader.CreateStreamProviderRegistry` method gets called at`ShapefileDataReader` constructor. It passes `encoding.EncodingName` to `ByteStreamProvider` argument with `"Unicode (UTF-8)"` value.
> 
> Later, when parsing the header in `NetTopologySuite.IO.DbaseFileHeader.GetEncoding()`
> 
> ```cs
> try
> {
>     // The following line throws exception
>     // 'Unicode (UTF-8)' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
>     return DbaseEncodingUtility.GetEncodingForCodePageName(cpgText);
> }
> catch
> {
>     return DefaultEncoding;
> }
> ```
> 
> I think `DbaseEncodingUtility.GetEncodingForCodePageName` should be called with "UTF-8" argument.
> 
> **Registering encoding provider** Calling `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);` does not fixes my issue.
> 
> **Quick fix** Setting the default header encoding.
> 
> ```cs
> DbaseFileHeader.DefaultEncoding = Encoding.UTF8;
> ```

May I ask how the solution was finally solved? Could you share the method?

**Comment by KubaSzostak** [comment]
Support for a different encodings has been added in the [successor](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri) library. There is also a [sample code](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/blob/develop/test/NetTopologySuite.IO.Esri.Test/Deprecated/Headers/ShapeFileEncodingTest.cs) demonstrating how to custom encoding.
