### ISSUE TITLE
How to change the way a Shapefile is decoded when reading from it?

### ISSUE THREAD

**Issue by MaximilianBottin** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#26]
Hello NetTopologySuite-Team,
I got a question about reading Shapefiles (.shp) with NetTopologySuite.IO.
Is there any way to set the Encoding for the file to be read? All the Shapefiles I get are encoded using Windows-1252. But because I'm using DotNetCore it tries to encode every file as UTF-8 which is problematic with any special characters like ß, ü, ä, ö and so on which just return a "?" as a character instead.

Can someone please provide me with an example of how to read a shp File encoded in Windows-1252 correctly? 

I don't need to write any changes to the Shapefile just read the data in the correcly encoded format.

I've attached a Shapefile where this problem occurs.
[SCHLAG.zip](https://github.com/NetTopologySuite/NetTopologySuite/files/3926917/SCHLAG.zip)

**Comment by airbreather** [comment]
> reading Shapefiles (.shp) with NetTopologySuite.IO

The package to use is [NetTopologySuite.IO.ShapeFile](https://www.nuget.org/packages/NetTopologySuite.IO.ShapeFile).  1.15.3 is the version to use with NetTopologySuite 1.x, 2.0.0 is the version to use with NetTopologySuite 2.x.

The encoding is actually stored in the .dbf file itself (edit: or a .cpg file), which we read [around here](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/blob/6bf402a697d1ef2cb665bd56a28a50f4dcc47830/src/NetTopologySuite.IO.ShapeFile/Dbase/DbaseFileHeader.cs#L292-L294) and interpret [around here](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/blob/6bf402a697d1ef2cb665bd56a28a50f4dcc47830/src/NetTopologySuite.IO.ShapeFile/Dbase/DbaseFileHeader.cs#L368-L378).

If it's truly encoded in Windows-1252, then the LDID [should be 0x58](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/blob/6bf402a697d1ef2cb665bd56a28a50f4dcc47830/src/NetTopologySuite.IO.ShapeFile/Dbase/DbaseEncodingUtility.cs#L70).

The attached zip file only has a .shp file... was there not a .dbf file that came with it?

**Comment by MaximilianBottin** [comment]
Thanks for the quick reply.
So far I never opened any of the others because all the information I needed was stored in the
.shp File
There is a .dbf file inside.

How would I have to proceed in order to read the contents of the dbf file and apply the encoding from there to the .shp File?

So far I was using this approach which gave me all the data I needed:

```C#
var reader = new ShapeDataReader(shpPath);
var result = reader.ReadByMBRFilter(reader.ShapefileBounds);
var shapes = result.ToList();
```

I've attached all the files I get with every .shp file below

[All Files.zip](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/files/3927243/All.Files.zip)

**Comment by MaximilianBottin** [comment]
Thanks for the help, I've realized that all the information of the shapefile is also contained in the dbf-File. So I use the Shapefile for the geometry-data and the dbf-File for the data.
Also the dbf-file is in a readable ANSI-Format so to mitigate the encoding issue I just opened the file with Windows-1252 Encoding. And then wrote the content to a new file with UTF-8 Encoding and now the DBF-Files content is correctly read by DotNetCore.

Edit: Okay the above method didn't work as the DbaseReader class can't parse the UTF-8 Encoded File. Is there any way to open the dbf-File with the correct encoding?
I used the DbaseFileReader which correctly tells me that the File is Encoded with Windows-1252 but when I try to get the data it with DbaseReader it is still read as UTF-8 instead of Windows-1252.

![image](https://user-images.githubusercontent.com/7858083/70424861-5d2b4e80-1a70-11ea-9e46-2a65f54c8822.png)

![image](https://user-images.githubusercontent.com/7858083/70425538-b0ea6780-1a71-11ea-892d-2ffce6b7b223.png)

**Comment by airbreather** [comment]
You're running into #25 and (I think) #19.

Here's code to translate a shapefile from one encoding to another, working around all those bugs:

```csharp
string readFile = @"C:\Temp\SCHLAG.shp";
string writeFile = @"C:\Temp\SCHLAG-utf8.shp";
var readEncoding = CodePagesEncodingProvider.Instance.GetEncoding(1252);
var writeEncoding = Encoding.UTF8;

var factory = NtsGeometryServices.Instance.CreateGeometryFactory();

// BUG #25: we shouldn't need to set this here.
DbaseFileHeader.DefaultEncoding = readEncoding;

DbaseFileHeader readHeader;
List<Feature> features;

// we should AT MOST only have to specify readEncoding here
// ideally the DBF header would include an LDID, in which case
// we should in theory be able to skip it here too.
using (var rd = new ShapefileDataReader(readFile, factory, readEncoding))
{
    readHeader = rd.DbaseHeader;

    string[] fieldNames = new string[readHeader.NumFields];
    features = new List<Feature>(readHeader.NumRecords);

    for (int i = 0; i < fieldNames.Length; i++)
    {
        // +1 because the first field is the geometry.
        fieldNames[i] = rd.GetName(i + 1);
    }

    while (rd.Read())
    {
        var attributes = new AttributesTable();
        for (int i = 0; i < fieldNames.Length; i++)
        {
            // +1 because the first field is the geometry.
            attributes.Add(fieldNames[i], rd.GetValue(i + 1));
        }

        features.Add(new Feature(rd.Geometry, attributes));
    }
}

// BUG #19: we shouldn't need to set this up here, but
// for some reason, AddColumn grabs the default if we don't.
var writeHeader = new DbaseFileHeader(writeEncoding)
{
    LastUpdateDate = readHeader.LastUpdateDate,
    NumRecords = readHeader.NumRecords,
};
foreach (var field in readHeader.Fields)
{
    writeHeader.AddColumn(field.Name, field.DbaseType, field.Length, field.DecimalCount);
}

// this is the only place we should need to pass in writeEncoding:
var wr = new ShapefileDataWriter(writeFile, factory, writeEncoding)
{
    Header = writeHeader,
};

wr.Write(features);
```

**Comment by MaximilianBottin** [comment]
Great, thanks alot I'll use your code-snippet to get mine to work. 
Right now I've found another dirty workaround where I manually read the dbf-File as text and get the correct Names, but when I got time for refactoring I will implement your example.

I think my issue is resolved now, so I'll close this one.

**Comment by phungxuanvuong** [comment]
I just have tried the file you upload above:

Before convert: stösst auf den rendeler pfad
After convert: stÃ¶sst auf den rendeler pfad

Is that work correctly?

**Comment by phungxuanvuong** [comment]
@airbreather How can I check that what is the encoding of shapefile?

**Comment by MaximilianBottin** [comment]
@vuggg It should be exactly the other way around:
Before: stÃ¶sst
After: stösst
Tried the code above and it worked for me though.
