### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#3]
Running all the NUnit tests from a clean clone on VS2017, most of them fail on my machine.

Some of the failures are because the tests are run on `netcoreapp2.0` (so using `netstandard2.0`), which doesn't handhold as much as the "fat" .NET targets and has a few different defaults around encodings.

**Comment by airbreather** [comment]
(I don't have permissions to assign this to myself, but I'm on it)

**Comment by xivk** [comment]
@airbreather I think you now have permissions to manage this repo as you see fit. I'll come back to this at some point, just not sure when at the moment.
