### ISSUE TITLE
Does this module support UWP and Android (.NETStandard)?

### ISSUE THREAD

**Issue by FelixKainz** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#35]
I am creating a Xamarin.Forms App across UWP and Android with .NetStandard.

Since I have a thight deadline a quick answer would be great!

Thank you very much!

**Comment by airbreather** [comment]
The latest versions of NetTopologySuite projects target .NET Standard 2.0.

See [this table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) for an up-to-date list of platforms that support .NET Standard 2.0; reproduced here, current as of the time of this comment:

1. .NET Framework 4.6.1 thru .NET Framework 4.7.1 (with varying degrees of stress)
1. .NET Framework 4.7.2+ (mostly smoothly)
1. .NET Core 2.0 or higher
1. Mono 5.4 or higher
1. Xamarin.iOS 10.14 or higher
1. Xamarin.Mac 3.8 or higher
1. Xamarin.Android 8.0 or higher
1. Universal Windows Platform 10.0.16299 or higher
1. Unity 2018.1 or higher
