### ISSUE TITLE
Whitespaces in cpg file prevents to detect correct encoding.

### ISSUE THREAD

**Issue by Alexey-Stolyarov** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#38]
In this line you're trying to use content of cpg file as is. But whitespaces, line endings, etc prevents to detect correct encoding. 
https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/blob/bef5ec80cc5b1b5a95f4df3bfc5a61ab837525a1/src/NetTopologySuite.IO.ShapeFile/Dbase/DbaseFileHeader.cs#L511

E.g. these lines will lead to ArgumentException which will lead to default encoding instead of desirable.
```
Encoding.GetEncoding("UTF-8/r/n")
Encoding.GetEncoding("UTF-8 ")

```

Suggestion - trim leading and trailing whitespaces.

**Comment by KubaSzostak** [comment]
Support for a different encodings has been added in the [successor](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri) library. There is also a [sample code](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/blob/develop/test/NetTopologySuite.IO.Esri.Test/Deprecated/Headers/ShapeFileEncodingTest.cs) demonstrating how to custom encoding.
