### ISSUE TITLE
Redo everything

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#48]
Following from #42, we should probably just redo all the shapefile reading code.

It would be nice not to use any of the code from the other library so that we can provide a library that's licensed under BSD-3-clause instead of LGPL.

**Comment by airbreather** [comment]
I've started some work at https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/tree/wip/ng

It's really really early, so don't expect much from it yet, I'm just indicating this so that we don't duplicate efforts.

**Comment by KubaSzostak** [comment]
https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/releases/tag/v1.0
