### ISSUE TITLE
How to read AttributeTable

### ISSUE THREAD

**Issue by qiangwai** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#52]
I want get ShapeFile's AttributeTable ,I did it this way
```
ShapefileDataReader dataReader = new ShapefileDataReader(shapepath, Factory, Encoding.UTF8);
for (int i = 1; i < fieldNames.Length; i++)
                    {
                        attributesTable.Add(fieldNames[i], dataReader.GetValue(i));
                    }
```
but Why dataReader's depth is 0,result in an empty reference exception to be thrown.My shp can be read in ArcMap.Is My method wrong? What is the general way  to read AttributeTable?

**Comment by DGuidi** [comment]
see [this sample](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/blob/576f26573342615a0a5f5d6a3b33dcfcbd5b8ee8/test/NetTopologySuite.IO.ShapeFile.Test/ShapeFileDataReaderTest.cs#L45)

```
using (var reader = new ShapefileDataReader("crustal_test_bugged", Factory))
{
 int length = reader.DbaseHeader.NumFields;
 while (reader.Read())
 {
  Debug.WriteLine(reader.GetValue(length - 1));
 }
}
```

You missed the `reader.Read()`, that is basically the standard pattern when reading data from any source in .net

**Comment by qiangwai** [comment]
yes,you are right.@DGuidi  But I have another question ,dataReader.GetValue[i]and dataReader.Geometry only support one Geometry and it's value？My Shape is multi Geometry ,I want read multi attribute ,How should I read?

**Comment by DGuidi** [comment]
It's not the way it works. A multi-geometry it's a single geometry object, so it has a single set of attributes: a multipoint is a single geometry composed of a number of points, and all these points share the same set of attributes, like a single geometry do.

**Comment by qiangwai** [comment]
I’m sorry to bother you@DGuidi.I mean one shape can have more than one geometry, that is, a attributetable can have more than one attribute, like this
![image](https://user-images.githubusercontent.com/41463375/99467950-67d9ad80-297a-11eb-8150-d877a9af0581.png)
I know that a multipoint can share one attribute.

**Comment by qiangwai** [comment]
Thank you@DGuidi .Now I can read all attributes.But sometimes  messy code characters appear in attributes when read contains chinese character shape.How can i solve this problem? like this shape
[anhui_shp.zip](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/files/5559096/anhui_shp.zip)

**Comment by DGuidi** [comment]
maybe related to #39

**Comment by DGuidi** [comment]
BTW if you had some troubles with the attribute values, you can use this code that I thik should be already working
```
var encoding = DbaseEncodingUtility.GetEncodingForCodePageIdentifier(936);
using var reader = new ShapefileDataReader("chinese_encoding.shp", Factory, encoding);
// read your data
```

#39 should fix actually only the problems related to field names, but attribute values shall be already read using the valid encoding

**Comment by DGuidi** [comment]
please check if last commit fix the issue, as expected
