### ISSUE TITLE
String values are trimmed when read using DbaseFileReader

### ISSUE THREAD

**Issue by kristofdegrave** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#63]
When we write a string value that starts or ends with a space in a dbase file, these spaces are removed when reading the value.

https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/blob/3c952d5df92d1b5cc3c78b7f9d4815f129c2b719/src/NetTopologySuite.IO.ShapeFile/Dbase/DbaseFileReader.cs#L163

Are there any specific reasons why this is done? I would expect to get the result back, the way I wrote it in the file.

**Comment by KubaSzostak** [comment]
According to the [dBASE](https://www.dbase.com/Knowledgebase/INT/db7_file_fmt.htm) specification Character (C) field is "_padded with blanks to the width of the field_". Therefore all spaces have to be trimmed, as per specification.
