### ISSUE TITLE
Geometry with only Z aren't supported

### ISSUE THREAD

**Issue by kristofdegrave** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#68]
I see that in the `ShapeGeometryType` geometries with only an additional Z value are present, but when reading a such a value, they aren't added. I see some comment that states that they are unofficial, but I don't find this in the provided link.

Is it possible to also implement this? This is a missing feature for me. I have some cases where I need to read a geometry like `PolygonZ`

**Comment by FObermaier** [comment]
According to the [Shapefile spec](https://www.esri.com/Library/Whitepapers/Pdfs/Shapefile.pdf) 10ff and 15ff, there is no `XYZ` geometry type in Shapefiles. Its either `XY`, `XYM` or `XYZM`.
In other words The Z-shape types always carry an additional M-value.

**Comment by kristofdegrave** [comment]
@FObermaier I see, but can I produce a PR that allows to read an `XYZ` geometry? I understand that writing such type shouldn't be allowed, but allow reading would make it a bit more flexible.

**Comment by FObermaier** [comment]
You want to change the reader to return a `XYZ` Geometry when reading a M type shape?
I don't see where that would hurt.

**Comment by KubaSzostak** [comment]
Closing this issue because there has been no response to our request for more information. Please reach out if you have or find the answers we need so that we can investigate further.
