### ISSUE TITLE
ShapeFileDataReader Unable to parse shape file properly

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#7]
_From @Labbe21 on October 30, 2017 15:35_

I have a shape file generated with QGIS as a zip with dbf, prj, shp and shx files within it.

That file decoding is fine with QGIS Tool and https://mygeodata.cloud/converter/

However, ShapefileDataReader is not able to read all columns as expected.
Most of columns are parsed as ""\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0" with various number of occurences of "\0" while some columns are ok.

There is the file I'm trying to parse: https://ufile.io/p0zl3

I am using the last version of NetTopologySuite.

Could someone please help me with this issue, I'm running out of ideas to fix this problem.

_Copied from original issue: NetTopologySuite/NetTopologySuite#202_

**Comment by airbreather** [comment]
_From @xivk on November 8, 2017 10:42_

What packages are you using exactly?

**Comment by KubaSzostak** [comment]
We have requested more information regarding this issue, but have not received a response or additional information regarding this issue. Therefore, we are closing this issue.
