### ISSUE TITLE
How to update existing shape file

### ISSUE THREAD

**Issue by Zeleksonob** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#72]
Hi All , 
I managed to read from a shapefile and create a new shapefile and write to it , but I didn't see any example of how to update existing shapefile features.  any can help with this? 

Thanks.

**Comment by DGuidi** [comment]
no specific support for this: you should read the data, modify the features and then write the modified data in a new file

**Comment by KubaSzostak** [comment]
If you want update feature attributes, then from technical point of view it is possible. DBF records have fixed size, so they can be updated in place. It is not supported by this library, though. If you want update SHP geometry, then it is not possible. Shapefile is a variable-record-length file in which each record describing a shape can have different size. So there is no way to update it in place.
