### ISSUE TITLE
DbaseFileHeader.DetectEncoding method should be modified

### ISSUE THREAD

**Issue by rgbcmy** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#73]
this method reference http://downloads.esri.com/support/documentation/pad_/ArcPad_RefGuide_1105.pdf;
 
![image](https://user-images.githubusercontent.com/24647300/124227704-af91fb80-db3d-11eb-9c03-4ac3c3c72801.png)
The pdf first is Check for DBF LDID,but the method  first is Check for CPG ;and  the method  ShapefileDataReader(string filename, GeometryFactory geometryFactory, Encoding encoding) if   the parameter encoding is null and .CPG file not exist, ShapefileStreamProviderRegistry.DataEncodingStream also have default,so LDID  Not available at all。I think it should be modified to
```
private static Encoding DetectEncoding(byte ldid, IStreamProvider cpgFile)
        {
           

            if (DbaseEncodingUtility.LdidToEncoding.TryGetValue(ldid, out Encoding value))
            {
                return value;
            }
           if (cpgFile != null)
            {
                return GetEncoding(cpgFile);
            }
            return DefaultEncoding;
        }
```

**Comment by DGuidi** [comment]
Actually, I have mixed feelings about taking ArcPad specifications as a general reference: do you know any info about other software that handles cpg in the same way? 
In any case, my two cents: cpg is an optional file, so info in cpg should override the "default" info in header; so, to me the current code it's ok. 
![5gc412](https://user-images.githubusercontent.com/216627/125469320-5ce90d6f-8b62-408d-9e16-f009416c3356.jpg)

**Comment by DGuidi** [comment]
Actually, I have mixed feelings about taking ArcPad specifications as a general reference: do you know any info about other software that handles cpg in the same way? 
In any case, my two cents: cpg is an optional file, so info in cpg should override the "default" info in header. So to me the current code it's ok. 
![5gc412](https://user-images.githubusercontent.com/216627/125469320-5ce90d6f-8b62-408d-9e16-f009416c3356.jpg)

**Comment by rgbcmy** [comment]
> Actually, I have mixed feelings about taking ArcPad specifications as a general reference: do you know any info about other software that handles cpg in the same way?
> In any case, my two cents: cpg is an optional file, so info in cpg should override the "default" info in header; so, to me the current code it's ok.
> ![5gc412](https://user-images.githubusercontent.com/216627/125469320-5ce90d6f-8b62-408d-9e16-f009416c3356.jpg)

I mean if  cpg file not  exist 
ShapefileStreamProviderRegistry.DataEncodingStream has a default  so  it never to read dbf Ldid

**Comment by rgbcmy** [comment]
I mean if cpg file not exist
ShapefileStreamProviderRegistry.DataEncodingStream has a default so it never to read dbf Ldid

**Comment by DGuidi** [comment]
> ShapefileStreamProviderRegistry.DataEncodingStream has a default so it never to read dbf Ldid

This comment does not make sense to me, sorry.
Anyway, you can see the actual code [here](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/blob/develop/src/NetTopologySuite.IO.ShapeFile/Dbase/DbaseFileHeader.cs#L369) and it follows the ArcPad specifications, so forgot my "mixed feelings"...
I will close this issue, if you think the problem still persist feel free to re-open the issue, but please be specific about the problem, the expected behavior and possibly add some code and data that reproduces the problem.
