### ISSUE TITLE
GDB missing

### ISSUE THREAD

**Issue by reubenShilling** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#77]
Am I nuts or is NetTopologySuite.IO.GDB completely missing from the nuget package?

**Comment by DGuidi** [comment]
the GDB-related code is in the "IO.ShapeFile" nuget package, you don't need to add another package to your solution

**Comment by airbreather** [comment]
> the GDB-related code is in the "IO.ShapeFile" nuget package, you don't need to add another package to your solution

I didn't think so... can you please double-check?

**Comment by DGuidi** [comment]
Ok, the GDB-related code is in this github repository, [here](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/tree/develop/src/NetTopologySuite.IO.GDB), so I assumed that the same code is deployed in the same package.   
I checked and you're right, actually GDBReader/Writer classes looks not deployed inside the nuget package.

**Comment by DGuidi** [comment]
as in the [release description](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/releases/tag/v2.0.0)

> There's now just one DLL, "NetTopologySuite.IO.Shapefile.dll"

sorry for the mistake

**Comment by airbreather** [comment]
We can probably just move `GDBReader` and `GDBWriter` into the main project?

**Comment by DGuidi** [comment]
makes sense to me, but probably we should also remove "VeDEx" references in the comments, that is a reference to a product I was working on probably 15 years ago!

**Comment by reubenShilling** [comment]
> We can probably just move `GDBReader` and `GDBWriter` into the main project?

Thanks for the quick response guys!
So am I correct in saying that as of now these two classes are not included in any NTS nuget package?

**Comment by DGuidi** [comment]
Yep, absolutely
