### ISSUE TITLE
Publish release with ExternallyManagedStreamProvider

### ISSUE THREAD

**Issue by agrian-joel** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#78]
I'd like to use this library with the changes from https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/pull/58

Can a new release be published for this?

**Comment by KubaSzostak** [comment]
Support for a custom-managed stream, which allows shapes to be written to it, [has been added](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/pull/36) in the [successor](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri) library. There is also a [sample code](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/blob/develop/test/NetTopologySuite.IO.Esri.Test/Issues/Issue041.cs)  demonstrating how to use streams.
