### ISSUE TITLE
Issue with 'L' Column in DBF with Length greater than 1.

### ISSUE THREAD

**Issue by mahdirastegari** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#87]
I encountered a shapefile with an 'L' column where the Length is greater than 1. However, when reading the logical column, there is a mismatch at the start of the reader. 

Below is an image to illustrate the mismatch I'm referring to.

![image](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/assets/8531566/8472d54b-b650-4761-afc3-e71a17bb1474)

Here is the shape file zipped which I face the issue.
[roads4.zip](https://github.com/user-attachments/files/16055940/roads4.zip)

Although I understand that the Logic column should have a Length of 1, other importers such as QGIS can import this file correctly, so I believe we should address the issue.

**Comment by mahdirastegari** [comment]
I believe we're encountering the same problem with the Date issue because we're only reading 8 bytes. According to the code, if the shapefile date column is exported with a size other than 8, we'll encounter the same problem.

If everyone agrees that this is the case, I can submit a pull request to resolve the issue for both 'L' and 'D' column types.

**Comment by FObermaier** [comment]
This package is deprecated, please use the [successor](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri).

**Comment by KubaSzostak** [comment]
Fixed by https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/issues/51. Thank you @mahdirastegari.
