### ISSUE TITLE
prj get coordinatesystem

### ISSUE THREAD

**Issue by sigster** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#89]
Hi how cad I get coordinatesystem of a shapefile from prj file

**Comment by FObermaier** [comment]
This project is deprecated, please use NetTopologySuite.IO.Esri instead.

**Comment by KubaSzostak** [comment]
Closed as a duplicate of https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/issues/56
